name: SDK Tests
on:
  pull_request:
    paths:
        - 'sdk/**'
    branches:
      - main
defaults:
  run:
    working-directory: sdk
jobs:
  test:
    runs-on: ubuntu-20.04
    name: Python ${{ matrix.python-version }}
    strategy:
      matrix:
        python-version: ['3.7.x', '3.8.x']
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Install dependencies
        run: make install-deps
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Test
        run: make test
